claim_front_index:
    path:     /
    defaults: { _controller: "ECommerceBundle:Claim:index" }

claim_front_new:
    path:     /new
    defaults: { _controller: "ECommerceBundle:Claim:new" }

my_claims:
    path:     /my
    defaults: { _controller: "ECommerceBundle:Claim:getClaims" }
