claim_index:
    path:     /
    defaults: { _controller: "ECommerceBundle:Claim:index" }

claim_show:
    path:     /{id}/show
    defaults: { _controller: "ECommerceBundle:Claim:show" }

claim_new:
    path:     /new
    defaults: { _controller: "ECommerceBundle:Claim:new" }

claim_edit:
    path:     /{id}/edit
    defaults: { _controller: "ECommerceBundle:Claim:edit" }

claim_delete:
    path:     /{id}/delete
    defaults: { _controller: "ECommerceBundle:Claim:delete" }
