_promotion_index:
    path:     /
    defaults: { _controller: "ECommerceBundle:Promotion:index" }
    methods:  [GET, POST]

_promotion_show:
    path:     /{id}/show
    defaults: { _controller: "ECommerceBundle:Promotion:show" }
    methods:  GET

_promotion_new:
    path:     /new
    defaults: { _controller: "ECommerceBundle:Promotion:new" }

_promotion_create:
    path:     /create
    defaults: { _controller: "ECommerceBundle:Promotion:create" }
    requirements: { _method: post }

_promotion_update:
    path:     /{id}/update
    defaults: { _controller: "ECommerceBundle:Promotion:update" }


_promotion_edit:
    path:     /{id}/edit
    defaults: { _controller: "ECommerceBundle:Promotion:edit" }


_promotion_delete:
    path:     /{id}/delete
    defaults: { _controller: "ECommerceBundle:Promotion:delete" }
    methods:  [GET, DELETE]
_promotion_index_list:
    path:     /list
    defaults: { _controller: "ECommerceBundle:Promotion:list" }
    methods:  [GET, POST]


