gaming_coupon:
    resource: "@GamingBundle/Resources/config/routing/coupon.yml"
    prefix:   /coupon

gaming_homepage:
    path:     /
    defaults: { _controller: GamingBundle:Default:index }

flappy_page:
    path:     /flappy
    defaults: { _controller: GamingBundle:Default:flappy }
_generate_coupon:
    path:     /coupon/generate
    defaults: { _controller: GamingBundle:Coupon:generate }