<?php

namespace ECommerceBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPromotionBystartDate() {
        $query=$this->getEntityManager()
            ->createQuery(" Select  p from ECommerceBundle:Promotion p Order by p.startingDate ")->setMaxResults(1);

        return $query->getSingleResult();


    }
}
