<?php

namespace ECommerceBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRateByProductAndUser($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(" SELECT r FROM ECommerceBundle:Rating r  WHERE IDENTITY(r.products) = :id_produit 
            ORDER BY r.id DESC ")
            ->setParameter('id_produit', $id)
            ->setMaxResults(1);
        return $query->getResult();
    }

    public function countRate($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(" SELECT COUNT (r) FROM ECommerceBundle:Rating r  WHERE IDENTITY(r.products)= :id_produit 
            ")
            ->setParameter('id_produit', $id)
            ;
        return $query->getResult();
    }
    public function avgRate($id)
    {
        $query = $this->getEntityManager()
            ->createQuery(" SELECT AVG (r.note) FROM ECommerceBundle:Rating r  WHERE IDENTITY(r.products)= :id_produit 
            ")
            ->setParameter('id_produit', $id)
        ;
        return $query->getResult();
    }
}
