app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
formation:
    resource: "@FormationBundle/Resources/config/routing.yml"
    prefix:   /

training:
    resource: "@TrainingBundle/Resources/config/routing.yml"
    prefix:   /

pastry:
    resource: "@PastryBundle/Resources/config/routing.yml"
    prefix:   /

gaming:
    resource: "@GamingBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

e_commerce:
    resource: "@ECommerceBundle/Resources/config/routing.yml"
    prefix:   /

back_office:
    resource: "@BackOfficeBundle/Resources/config/routing.yml"
    prefix:   /admin

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fados_fullcalendar:
    resource: "@EventBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_pastry_homepage:
    path:     /pastryList
    defaults: { _controller: PastryBundle:Pastry:listPastry }
mgilet_notifications:
    resource: "@MgiletNotificationBundle/Controller/"
