pastry_homepage:
    path:     /
    defaults: { _controller: PastryBundle:Pastry:indexPastry }

add_pastry:
    path:     /addPastry
    defaults: { _controller: PastryBundle:Pastry:addPastry }

show_pastry:
    path:     /showPastry/{id}
    defaults: { _controller: PastryBundle:Pastry:showPastry }


update_pastry:
    path:     /updatePastry
    defaults: { _controller: PastryBundle:Pastry:updatePastry }

del_pastry:
    path:     /delPastry/{id}
    defaults: { _controller: PastryBundle:Pastry:delPastry }

add_ingredient:
    path:     /addIngredient
    defaults: { _controller: PastryBundle:Ingredient:addIngredient }

show_ingredient:
    path:     /showIngredient
    defaults: { _controller: PastryBundle:Ingredient:showIngredient }

update_ingredient:
    path:     /updateIngredient
    defaults: { _controller: PastryBundle:Ingredient:updateIngredient }

del_ingredient:
    path:     /delIngredient
    defaults: { _controller: PastryBundle:Ingredient:delIngredient }
