contact_index:
    path:     /
    defaults: { _controller: "AppBundle:Contact:index" }
    methods:  [GET, POST]

contact_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Contact:show" }
    methods:  GET


contact_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Contact:update" }


contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Contact:edit" }


contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Contact:delete" }
    methods:  [GET, DELETE]


