contact_index:
    path:     /
    defaults: { _controller: "AppBundle:Contact:index" }
    methods:  [GET, POST]

contact_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Contact:show" }
    methods:  GET


contact_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Contact:update" }

contact_new:
    path:     /new
    defaults: { _controller: "AppBundle:Contact:new" }

contact_create:
    path:     /create
    defaults: { _controller: "AppBundle:Contact:create" }
    requirements: { _method: post }

contact_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Contact:edit" }


contact_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Contact:delete" }
    methods:  [GET, DELETE]

contact_archive:
    path:     /archive
    defaults: { _controller: "AppBundle:Contact:archive" }
    methods:  [GET, POST]

contact_history:
    path:     /
    defaults: { _controller: "AppBundle:Contact:index" }
    methods:  [GET, POST]
