<?php

namespace EventBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast() {
        $query=$this->getEntityManager()
            ->createQuery(" Select  e.id from EventBundle:Event e Order by e.id DESC")->setMaxResults(1);

        return $query->getSingleResult();


    }
}
