<?php

namespace EventBundle\Repository;

/**
 * ParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUser($key)
    {
        $query=$this->getEntityManager()
            ->createQuery(" Select  u from UserBundle:User u where u.username LIKE :username ")
            ->setParameter('username','%'.$key.'%');

        return $query->getResult();
    }
}
