e_commerce_product:
    resource: "@ECommerceBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product
e_commerce_promotion:
    resource: "@ECommerceBundle/Resources/config/routing/promotion.yml"
    prefix:   /admin/promotion

e_commerce_claim:
    resource: "@ECommerceBundle/Resources/config/routing/claim.yml"
    prefix:   /claim
e_commerce_commande:
    resource: "@ECommerceBundle/Resources/config/routing/commande.yml"
    prefix:   /commande
e_commerce_delivery:
    resource: "@ECommerceBundle/Resources/config/routing/delivery.yml"
    prefix:   /delivery
_cupcakes_product-grid:
    path:     /product-grid
    defaults: { _controller: ECommerceBundle:Default:ProductGrid }
_cupcakes_product-detail:
    path:     /product-detail
    defaults: { _controller: ECommerceBundle:Default:ProductDetail}
_cupcakes_product-listing:
    path:     /product-listing
    defaults: { _controller: ECommerceBundle:Default:ProductListing}
_cupcakes_cart:
    path:     /cart
    defaults: { _controller: ECommerceBundle:Default:Cart }

_cupcakes_order_form:
    path:     /order
    defaults: { _controller: ECommerceBundle:Default:OrderForm }
_cupcakes_checkout:
    path:     /checkout
    defaults: { _controller: ECommerceBundle:Default:Checkout }