e_commerce_product :
    resource: "@ECommerceBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product
    
e_commerce_promotion:
    resource: "@ECommerceBundle/Resources/config/routing/promotion.yml"
    prefix:   /admin/promotion
e_commerce_front_promotion:
    resource: "@ECommerceBundle/Resources/config/routing/promotion.yml"
    prefix:   /promotion
e_commerce_claim:
    resource: "@ECommerceBundle/Resources/config/routing/claim.yml"
    prefix:   /claim
#e_commerce_commande:
#    resource: "@ECommerceBundle/Resources/config/routing/commande.yml"
#    prefix:   /commande
#e_commerce_delivery:
#    resource: "@ECommerceBundle/Resources/config/routing/delivery.yml"
#    prefix:   /delivery
_cupcakes_product-grid:
    path:     /product-grid
    defaults: { _controller: ECommerceBundle:Product:showProductsByPrice }

_cupcakes_product-category:
    path:     /product-category
    defaults: { _controller: ECommerceBundle:Product:showProductsByCategory }
_cupcakes_product-search:
    path:     /product-search
    defaults: { _controller: ECommerceBundle:Product:findProducts }
_cupcakes_product-sort:
    path:     /product-sort
    defaults: { _controller: ECommerceBundle:Product:sortProducts }
_cupcakes_product-detail:
    path:     /product-detail/{id}
    defaults: { _controller: ECommerceBundle:Product:showProductDetails, id:'33'}
_cupcakes_product-listing:
    path:     /product-listing
    defaults: { _controller: ECommerceBundle:Product:showProducts}
_cupcakes_product-listing_By_Price:
    path:     /product-listing/{price1,price2}
    defaults: { _controller: ECommerceBundle:Product:showProductsByPrice}
_cupcakes_cart:
    path:     /Cart/{id}
    defaults: { _controller: ECommerceBundle:Default:Cart,id:'33' }
_cupcakes_order_form:
    path:     /OrderForm
    defaults: { _controller: ECommerceBundle:Default:OrderForm }
_cupcakes_checkout:
    path:     /Checkout
    defaults: { _controller: ECommerceBundle:Default:Checkout }