_cupcakes_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

_cupcakes_blog-listing:
    path:     /blog-listing
    defaults: { _controller: AppBundle:Blog:bloglisting }
_cupcakes_blog-detail:
    path:     /blog-detail
    defaults: { _controller: AppBundle:Blog:blogdetail }
_cupcakes_about:
    path:     /about
    defaults: { _controller: AppBundle:About:About }


_cupcakes_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:Contact }
