_cupcakes_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
_cupcakes_notif:
    path:     /notif
    defaults: { _controller: AppBundle:Default:notif }

_cupcakes_blog-listing:
    path:     /blog-listing
    defaults: { _controller: AppBundle:Blog:bloglisting }
_cupcakes_blog-detail:
    path:     /blog-detail
    defaults: { _controller: AppBundle:Blog:blogdetail }
_cupcakes_about:
    path:     /about
    defaults: { _controller: AppBundle:About:About }


_cupcakes_contact:
    path:     /contact
    defaults: { _controller: AppBundle:Contact:Contact }

my_app_mail_accuse:
    path: /success
    defaults: { _controller: AppBundle:Contact:success }
back_office_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:   /admin/contact

_Cupcakes_front_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Default:index}

