admin_homepage:
    path:     /
    defaults: { _controller: BackOfficeBundle:Default:index }

_admin:
    resource: "@BackOfficeBundle/Resources/config/routing/product.yml"
    prefix:   /product

back_office_actuality:
    resource: "@BackOfficeBundle/Resources/config/routing/actuality.yml"
    prefix:   /actuality
back_office_promotion:
    resource: "@BackOfficeBundle/Resources/config/routing/promotion.yml"
    prefix:   /promotion
back_office_event:
    resource: "@BackOfficeBundle/Resources/config/routing/event.yml"
    prefix:   /event
back_office_Pastry:
    resource: "@PastryBundle/Resources/config/routing.yml"
    prefix:   /pastry
