<?php

namespace PastryBundle\Repository;

/**
 * PastryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PastryRepository extends \Doctrine\ORM\EntityRepository
{
}
