claim_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Claim:index" }

claim_answer:
    path:     /answer/{id}
    defaults: { _controller: "BackOfficeBundle:Claim:answer" }

claim_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Claim:new" }

claim_create:
    path:     /create
    defaults: { _controller: "BackOfficeBundle:Claim:create" }

claim_update:
    path:     /{id}/update
    defaults: { _controller: "BackOfficeBundle:Actuality:update" }


claim_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Claim:edit" }

claim_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Actuality:delete" }
    methods:  [GET, DELETE]
claim_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Actuality:delete" }
    methods:  [GET, DELETE]


