claim_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Claim:index" }

claim_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:Claim:show" }
    methods:  GET

claim_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Claim:new" }

claim_create:
    path:     /create
    defaults: { _controller: "BackOfficeBundle:Claim:create" }

claim_update:
    path:     /{id}/update
    defaults: { _controller: "BackOfficeBundle:Actuality:update" }


claim_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Actuality:edit" }

claim_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:Actuality:delete" }
    methods:  [GET, DELETE]


