claim_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Claim:index" }

claim_answer:
    path:     /answer/{id}
    defaults: { _controller: "BackOfficeBundle:Claim:answer" }

claim_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:Claim:new" }

claim_create:
    path:     /create
    defaults: { _controller: "BackOfficeBundle:Claim:new" }

claim_update:
    path:     /{id}/update
    defaults: { _controller: "BackOfficeBundle:Actuality:update" }


claim_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:Claim:edit" }

_back_office_claim_delete:
    path:     /delete/{id}
    defaults: { _controller: "BackOfficeBundle:Claim:remove" }

