_back_office_event_index:
    path:     /
    defaults: { _controller: "BackOfficeBundle:Event:index" }

_back_office_promotion_show:
    path:     /{id}/show
    defaults: { _controller: "BackOfficeBundle:PromotionAdmin:show" }
    methods:  GET

_back_office_promotion_new:
    path:     /new
    defaults: { _controller: "BackOfficeBundle:PromotionAdmin:new" }

_back_office_promotion_create:
    path:     /create
    defaults: { _controller: "BackOfficeBundle:PromotionAdmin:create" }
    requirements: { _method: post }

_back_office_promotion_update:
    path:     /{id}/update
    defaults: { _controller: "BackOfficeBundle:PromotionAdmin:update" }


_back_office_promotion_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackOfficeBundle:PromotionAdmin:edit" }


_back_office_promotion_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackOfficeBundle:PromotionAdmin:delete" }
    methods:  [GET, DELETE]


