event_reservation:
    resource: "@EventBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

event_homepage:
    path:     /
    defaults: { _controller: EventBundle:Default:index }

event_event:
    resource: "@EventBundle/Resources/config/routing/event.yml"
    prefix:   /event
